# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t_53vtr966IxYjy3knlLeGBC0P2sEwoC
"""

import os

paths_to_check = ['/content/Lecture2_data.xlsx', '/Lecture2_data.xlsx']
for path in paths_to_check:
    exists = os.path.exists(path)
    print(f"File '{path}' exists: {exists}")

import pandas as pd

# Load the existing Excel file
file_path = '/Lecture2_data.xlsx'
try:
    df = pd.read_excel(file_path)
    print("File loaded successfully!")
    display(df.head())
except Exception as e:
    print(f"Error loading the file: {e}")

#Byjus case
import pandas as pd
import numpy as np

df = pd.read_excel("/Lecture2_data.xlsx")
display(df.head())

# Decision making structures
# Nested IF statement in python
revenue = df["Revenue_Lakh"].mean()
rating = df["Customer_Rating"].mean()

if revenue >= 300:
    print("Revenue is high")
    if rating >= 4:
        print("customer satisfaction is also good")
    else:
        print("customer satisfaction needs improvement")
else:
    print("revenue is low")

# Find the average customer rating
rating = df["Customer_Rating"].mean()

# Make a decision based on the rating
if rating >= 4.5:
  print("Excellent")

elif rating >= 4.0:
  print("Good")

elif rating >= 3.0:
  print("Average")

else:
  print("Needs Improvement")

# for loop
for rating in df["Customer_Rating"]:

    if rating >=4:
      print("Excellent")
    else:
      print("Needs Improvement")

# for loop with range() iloc= integer location
for i in range(10):
    print(df['Product'].iloc[i], df['Revenue_Lakh'].iloc[i])

i=0

while i<5:
  revenue=df['Revenue_Lakh'].iloc[i]
  if revenue>=300:
      print("High Revenue:",revenue)
  else:
      print('low revenue:',revenue)
  i=i+1