# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t_53vtr966IxYjy3knlLeGBC0P2sEwoC
"""

import os

paths_to_check = ['/content/Lecture2_data.xlsx', '/Lecture2_data.xlsx']
for path in paths_to_check:
    exists = os.path.exists(path)
    print(f"File '{path}' exists: {exists}")

import pandas as pd

# Load the existing Excel file
file_path = '/Lecture2_data.xlsx'
try:
    df = pd.read_excel(file_path)
    print("File loaded successfully!")
    display(df.head())
except Exception as e:
    print(f"Error loading the file: {e}")

#Byjus case
import pandas as pd
import numpy as np

df = pd.read_excel("/Lecture2_data.xlsx")
display(df.head())

# Decision making structures
# Nested IF statement in python
revenue = df["Revenue_Lakh"].mean()
rating = df["Customer_Rating"].mean()

if revenue >= 300:
    print("Revenue is high")
    if rating >= 4:
        print("customer satisfaction is also good")
    else:
        print("customer satisfaction needs improvement")
else:
    print("revenue is low")

# Find the average customer rating
rating = df["Customer_Rating"].mean()

# Make a decision based on the rating
if rating >= 4.5:
  print("Excellent")

elif rating >= 4.0:
  print("Good")

elif rating >= 3.0:
  print("Average")

else:
  print("Needs Improvement")

# for loop
for rating in df["Customer_Rating"]:

    if rating >=4:
      print("Excellent")
    else:
      print("Needs Improvement")

# for loop with range() iloc= integer location
for i in range(10):
    print(df['Product'].iloc[i], df['Revenue_Lakh'].iloc[i])

i=0

while i<5:
  revenue=df['Revenue_Lakh'].iloc[i]
  if revenue>=300:
      print("High Revenue:",revenue)
  else:
      print('low revenue:',revenue)
  i=i+1

import pandas as pd

# Define the file path for the Starbucks India Sales Dataset
starbucks_file_path = '/content/Starbucks_India_Sales_Dataset.xlsx'

# Load the dataset into a pandas DataFrame
try:
    starbucks_df = pd.read_excel(starbucks_file_path)
    print("Starbucks dataset loaded successfully!")
    display(starbucks_df.head())
except Exception as e:
    print(f"Error loading the file: {e}")

import pandas as pd

# Excel file path
FILE = "/content/Starbucks_India_Sales_Dataset.xlsx"

# Load the Excel sheets
df = pd.read_excel(FILE, sheet_name="Sales_Data")
products_df = pd.read_excel(FILE, sheet_name="Products")
stores_df = pd.read_excel(FILE, sheet_name="Stores")

# Check the data
print("Sales table:", df.shape)
print("Products:", products_df.shape)
print("Stores:", stores_df.shape)

# Display first 5 rows
df.head()

# ---- Part A: create them by typing ----

# LIST: the Starbucks menu (8 products)
menu = ["Cappuccino", "Latte", "Americano", "Cold Brew",
        "Frappuccino", "Masala Chai", "Blueberry Muffin", "Veg Sandwich"]

# TUPLE: one store's fixed details (StoreID, name, city)
store = ("S01", "Connaught Place", "Delhi")

# SET: cities where Starbucks sells (the duplicate 'Delhi' is removed automatically)
cities = {"Delhi", "Mumbai", "Bengaluru", "Hyderabad", "Pune", "Delhi"}

# DICTIONARY: product -> base price in Rs
price = {"Cappuccino": 250, "Latte": 270, "Americano": 220, "Cold Brew": 300,
         "Frappuccino": 350, "Masala Chai": 200, "Blueberry Muffin": 180, "Veg Sandwich": 240}

print("List      :", menu)
print("Tuple     :", store)
print("Set       :", cities, " <- 'Delhi' typed twice, stored once")
print("Dictionary:", price)
print()
print(type(menu), type(store), type(cities), type(price))

# ---- Part B: create them from the Excel data ----
# Each Excel column becomes a Python list. Each Excel row becomes a dictionary.

product_list = df["Product"].tolist()        # 100 products (with repeats)
city_list    = df["City"].tolist()           # 100 cities  (with repeats)
qty_list     = df["Quantity"].tolist()       # 100 quantities
revenue_list = df["Revenue"].tolist()        # 100 revenue values

first_order   = df.iloc[0].to_dict()                 # ONE order  -> dictionary
first_5_orders = df.head(5).to_dict("records")       # FIVE orders -> list of dictionaries

print("Items in product_list :", len(product_list))
print("Unique cities (set)   :", set(city_list))
print()
print("First order as a dictionary:")
print(first_order)

# --- List ---
print("First item      :", menu[0])
print("Last item       :", menu[-1])
print("First three     :", menu[0:3])      # slicing: start included, end excluded
print("Every 2nd item  :", menu[::2])

# --- Tuple (same as list) ---
print("\nStore ID        :", store[0])
print("Store city      :", store[2])

# --- Dictionary ---
print("\nPrice of Latte  :", price["Latte"])
print("Safe lookup     :", price.get("Pizza", "Not on menu"))   # no error if key is missing

# --- Set ---
print("\nIs Pune a Starbucks city?   ", "Pune" in cities)
print("Is Jaipur a Starbucks city? ", "Jaipur" in cities)

# --- Changing data: a list is changeable, a tuple is not ---
menu[6] = "Muffin"
print("Updated menu :", menu)
menu[6] = "Blueberry Muffin"          # change it back, we need the original name later

try:
    store[1] = "Saket Mall"
except TypeError as e:
    print("Tuple error  :", e)

# --- Access the real Excel data stored in Python structures ---
print("City of order #1       :", city_list[0])
print("Quantity of last order :", qty_list[-1])
print("First 5 revenues       :", revenue_list[:5])

print("\nProduct of first order :", first_order["Product"])
print("Revenue of first order :", first_order["Revenue"])

# list of dictionaries: [position][key]
print("\nCity of 3rd order      :", first_5_orders[2]["City"])
print("Product of 3rd order   :", first_5_orders[2]["Product"])

"""Section 3: Apply Functions to Data Structures (7 min)"""

# Built-in functions on the Revenue list (100 orders)
print("Number of orders   :", len(revenue_list))
print("Total revenue      : Rs", round(sum(revenue_list), 2))
print("Average order value: Rs", round(sum(revenue_list) / len(revenue_list), 2))
print("Biggest order      : Rs", max(revenue_list))
print("Smallest order     : Rs", min(revenue_list))
print("Top 5 orders       :", sorted(revenue_list, reverse=True)[:5])
print("Total cups/items   :", sum(qty_list))

# Count orders in each city

orders_per_city = {}

for c in city_list:

    if c in orders_per_city:
        orders_per_city[c] = orders_per_city[c] + 1
    else:
        orders_per_city[c] = 1

print("Orders per city:", orders_per_city)


# Find the busiest city
busiest_city = ""
highest_orders = 0

for c, orders in orders_per_city.items():

    if orders > highest_orders:
        highest_orders = orders
        busiest_city = c

print("Busiest city:", busiest_city)